export const DEFAULT_CHANNEL_TAG = 'Channel.Default';

export const NATIVE_GAMEPLAY_TAGS = [
  'Channel',
  DEFAULT_CHANNEL_TAG,
  'Combat',
  'Dungeon',
  'Character',
  'Character.Enemy',
  'Character.Enemy.Orc',
  'Character.Player',
  'Status',
  'Status.Debuff',
  'Status.Debuff.Vulnerable',
  'Status.Marked',
  'GameplayEvent',
  'GameplayEvent.Combat',
  'GameplayEvent.Combat.player',
  'GameplayEvent.Combat.player.StartTurn',
  'GameplayEvent.Combat.player.FinishTurn',
  'GameplayEvent.Combat.player.DrawACard',
  'GameplayEvent.Combat.player.PlayACard',
  'GameplayEvent.Combat.player.DealDamage',
  'GameplayEvent.Combat.player.TakeDamage',
  'GameplayEvent.Combat.player.NPC',
  'GameplayEvent.Combat.player.NPC.StartTurn',
  'GameplayEvent.Combat.player.NPC.FinishTurn',
  'EvaluationStage',
  'EvaluationStage.CommonDamage',
  'EvaluationStage.DamageOffset',
] as const;
