export type { ItemDefinition, ItemId } from './item-definition.js';
export {
  type EquipmentCardGrant,
  type EquipmentFragment,
  type DurabilityFragment,
  type ConsumableUseFragment,
  type PassiveEffectsFragment,
  type InventoryShapeFragment,
  type ItemFragment,
  type ItemInstanceState,
  type ItemFootprint,
  getEquipmentFragment,
  getDurabilityFragment,
  getInventoryShapeFragment,
  getItemFootprint,
  requiresItemInstance,
  createInitialInstanceState,
} from './fragments.js';
export {
  parseItemDefinition,
  buildItemCatalog,
  collectItemTagNames,
  type WireItemDefinition,
  type WireItemFragment,
} from './data/parse-item.js';
export {
  resolveRepoDataRoot,
  loadItemWiresFromDir,
  loadItemCatalogFromRepo,
  collectItemTagsFromRepo,
  loadBattleRewards,
  type BattleRewardEntry,
  type BattleRewardsTable,
} from './data/item-bootstrap.js';
export {
  DEFAULT_GRID_WIDTH,
  DEFAULT_GRID_HEIGHT,
  DEFAULT_INVENTORY_CAPACITY,
  createInventory,
  canAddToInventory,
  computeAddableQuantity,
  addToInventory,
  placeLootAt,
  canPlaceAt,
  findFirstFit,
  moveInventoryEntry,
  discardInventoryEntry,
  takeInventoryEntry,
  placePayloadInInventory,
  discardInventorySlot,
  tidyInventory,
  listInventorySlots,
  renderInventoryGrid,
  effectiveFootprint,
  resetItemInstanceCounter,
  type InventoryState,
  type InventoryPayload,
  type InventoryStackEntry,
  type InventoryInstanceEntry,
  type PlacedInventoryEntry,
  type InventoryAddResult,
  type InventorySlotView,
  type InventoryGridCell,
  type PlaceResult,
  type Rotation,
} from './inventory.js';
export {
  EQUIPMENT_SLOT_IDS,
  createEquipmentLoadout,
  equipFromInventory,
  unequipToInventory,
  listEquippedPieces,
  listEquipmentSlots,
  type EquipmentSlotId,
  type EquippedPiece,
  type EquipmentLoadout,
  type EquipResult,
  type EquipFailureReason,
  type EquipmentSlotView,
} from './equipment-loadout.js';
export { buildDeckIdsFromLoadout } from './deck-from-equipment.js';
export {
  createPendingLootFromTable,
  hasPendingLoot,
  listPendingLoot,
  pickupLootEntry,
  placePendingLootEntry,
  pickupAllLoot,
  validateBattleRewards,
  type PendingLootState,
  type PendingLootEntry,
  type LootEntryView,
  type PickupLootResult,
} from './loot.js';
export {
  createPendingLootFromCharacter,
  type CharacterLootRollEntry,
  type CharacterLootSource,
} from './character-loot.js';
